mysql:
  user: root
  password: Lxl&Mysql
  containerName: shealtiel-mysql
  dir: /Users/shealtiel/CodeBase/Personal/file-storage/docker/mysql/data
  dumpDir: /usr/bin/mysqldump
  adminDir: /usr/bin/mysqladmin
  database: -A
